Possibilità di ricaricare la pagina una volta che l'utente ha dato il…
Corsidia/it_cookie_law pull request #5
Opened 2020-02-18 21:05 UTC by progressify

… consenso

Imposta a true la variabile refreshAfterOptin

2020-02-19 07:31 UTC, duarme requested changes

2020-02-19 07:31 UTC, duarme commented on it_cookie_law.js
> +}
Add a newline at the end of file please :)

2020-02-19 07:31 UTC, duarme commented on it_cookie_law.js
> +var infoLinkText = "Leggi informativa";
Ops... thank you! I'm too used to writing code in ruby apperently....

2020-02-20 11:20 UTC, progressify commented
Ho aggiornato il README.md e aggiunto la nuova linea alla fine del file, ho anche aggiornato il master del mio fork, ma non ho capito se devo fare una nuova pull request o ti basta accettare questa per mergiare il tutto.

2020-02-20 11:24 UTC, merged

2020-02-20 11:24 UTC, darmenise commented
Mergiato il tutto 😄 grazie